# site settings

title: Nurbanu Kahraman Kurt
description: Software Developer
taglong: Software Developer
tagshort: Jekyll theme
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/nkahraman/nkahraman.github.io

# author settings

author:
  name: Nurbanu Kahraman Kurt
  email: nurbanukahraman7@gmail.com
photo: /assets/jpg/photo.jpg

# build settings

exclude:
  - LICENSE

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
